# -*- coding: utf-8 -*-
"""networked python program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cXCsPH4W3D9PO3VKITPp2xl5ylnqUnc9
"""

#server.py
import socket
port = 1234
address = "127.0.0.1"

# create a socket object name 'server'
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind((address, port))
server.listen(5)
print("Listening..")
while True:
    con, addr = server.accept()
    print ("Connection Address is: " , addr)
    con.send(bytes("Hello!, Welcome to the server!","utf-8"))

#client.py
import socket
port = 1234
address = '127.0.0.1'
BUF_SIZE = 1024

# create a socket object name 'con'
con = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
con.connect((address, port))

data = con.recv(BUF_SIZE)
con.close()
print(data.decode("utf-8"))